# BE CAREFUL MODIFYING THIS FILE
apiVersion: apps/v1
kind: Deployment
metadata:
  name: verification
spec:
  selector:
    matchLabels:
      app: verification
  replicas: 1
  template:
    metadata:
      labels:
        app: verification
    spec:
      containers:
      - name: verification
        image: gcr.io/gems-org/verification:dev
        command: ["./verification"]
        args: ["--env=ENV"]
        env:
        - name: VERIFICATION_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: verification-data
              key: VERIFICATION_DB_HOST
        - name: VERIFICATION_DB_PORT
          valueFrom:
            configMapKeyRef:
              name: verification-data
              key: VERIFICATION_DB_PORT
        - name: VERIFICATION_DBNAME
          valueFrom:
            configMapKeyRef:
              name: verification-data
              key: VERIFICATION_DBNAME
        - name: VERIFICATION_DB_USER
          valueFrom:
            configMapKeyRef:
              name: verification-data
              key: VERIFICATION_DB_USER
        - name: VERIFICATION_DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: verification-data
              key: VERIFICATION_DB_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: verification-data
              key: JWT_SECRET
        - name: REGISTRY_SVC_URL
          valueFrom:
            configMapKeyRef:
              name: verification-data
              key: REGISTRY_SVC_URL
        - name: RESPONSES_SVC_URL
          valueFrom:
            configMapKeyRef:
              name: verification-data
              key: RESPONSES_SVC_URL
        ports: 
        - containerPort: 8186
        resources: {}
      
---
apiVersion: batch/v1
kind: Job
metadata:
  name: verification-migration
spec:
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      labels:
        app: verification-migration
    spec:
      containers:
      - name: verification-migration
        image: gcr.io/gems-org/verification-migration-dev:dev
        args: ["composeup"]
        env:
        - name: VERIFICATION_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: verification-data
              key: VERIFICATION_DB_HOST
        - name: VERIFICATION_DB_PORT
          valueFrom:
            configMapKeyRef:
              name: verification-data
              key: VERIFICATION_DB_PORT
        - name: VERIFICATION_DBNAME
          valueFrom:
            configMapKeyRef:
              name: verification-data
              key: VERIFICATION_DBNAME
        - name: VERIFICATION_DB_USER
          valueFrom:
            configMapKeyRef:
              name: verification-data
              key: VERIFICATION_DB_USER
        - name: VERIFICATION_DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: verification-data
              key: VERIFICATION_DB_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: verification-data
              key: JWT_SECRET
      restartPolicy: Never
  backoffLimit: 4
---

apiVersion: v1
kind: Service
metadata:
  name: verification
spec:
  selector:
    app: verification
  ports:
  - port: 80
    targetPort: 8186
  type: LoadBalancer
