# BE CAREFUL MODIFYING THIS FILE
apiVersion: apps/v1
kind: Deployment
metadata:
  name: APP
spec:
  selector:
    matchLabels:
      app: APP
  replicas: 1
  template:
    metadata:
      labels:
        app: APP
    spec:
      containers:
      - name: APP
        image: gcr.io/ORG/NAME:VERSION
        command: ["./verification"]
        args: ["--env=ENV"]
        env:
        - name: VERIFICATION_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: DATA
              key: VERIFICATION_DB_HOST
        - name: VERIFICATION_DB_PORT
          valueFrom:
            configMapKeyRef:
              name: DATA
              key: VERIFICATION_DB_PORT
        - name: VERIFICATION_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: DATA
              key: VERIFICATION_DB_NAME
        - name: VERIFICATION_DB_USER
          valueFrom:
            configMapKeyRef:
              name: DATA
              key: VERIFICATION_DB_USER
        - name: VERIFICATION_DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: DATA
              key: VERIFICATION_DB_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: DATA
              key: JWT_SECRET
        - name: REGISTRY_SVC_URL
          valueFrom:
            configMapKeyRef:
              name: verification-data
              key: REGISTRY_SVC_URL
        - name: RESPONSES_SVC_URL
          valueFrom:
            configMapKeyRef:
              name: verification-data
              key: RESPONSES_SVC_URL
        ports: 
        - containerPort: 8186
        resources: {}
      
---
apiVersion: batch/v1
kind: Job
metadata:
  name: MIGRATION
spec:
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      labels:
        app: MIGRATION
    spec:
      containers:
      - name: MIGRATION
        image: gcr.io/ORG/NAME-migration:VERSION
        args: ["composeup"]
        env:
        - name: VERIFICATION_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: DATA
              key: VERIFICATION_DB_HOST
        - name: VERIFICATION_DB_PORT
          valueFrom:
            configMapKeyRef:
              name: DATA
              key: VERIFICATION_DB_PORT
        - name: VERIFICATION_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: DATA
              key: VERIFICATION_DB_NAME
        - name: VERIFICATION_DB_USER
          valueFrom:
            configMapKeyRef:
              name: DATA
              key: VERIFICATION_DB_USER
        - name: VERIFICATION_DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: DATA
              key: VERIFICATION_DB_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: DATA
              key: JWT_SECRET
      restartPolicy: Never
  backoffLimit: 4
---

apiVersion: v1
kind: Service
metadata:
  name: APP
spec:
  selector:
    app: APP
  ports:
  - port: 80
    targetPort: 8186
  type: LoadBalancer
