// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/service/service.go

// Package service is a generated GoMock package.
package service

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockBoilerplateService is a mock of BoilerplateService interface
type MockBoilerplateService struct {
	ctrl     *gomock.Controller
	recorder *MockBoilerplateServiceMockRecorder
}

// MockBoilerplateServiceMockRecorder is the mock recorder for MockBoilerplateService
type MockBoilerplateServiceMockRecorder struct {
	mock *MockBoilerplateService
}

// NewMockBoilerplateService creates a new mock instance
func NewMockBoilerplateService(ctrl *gomock.Controller) *MockBoilerplateService {
	mock := &MockBoilerplateService{ctrl: ctrl}
	mock.recorder = &MockBoilerplateServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockBoilerplateService) EXPECT() *MockBoilerplateServiceMockRecorder {
	return m.recorder
}

// Healthy mocks base method
func (m *MockBoilerplateService) Healthy() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Healthy")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Healthy indicates an expected call of Healthy
func (mr *MockBoilerplateServiceMockRecorder) Healthy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Healthy", reflect.TypeOf((*MockBoilerplateService)(nil).Healthy))
}
